title: Notas do Paulo
description: Notas sobre diversos temas, normalmente relacionados com tecnologia

show_downloads: false
google_analytics: UA-175717123-1
theme: jekyll-theme-hacker

plugins:
  - jekyll-include-cache
  - jekyll-seo